### ISSUE TITLE
Validação de formulário

### ISSUE THREAD

**Issue by Jp-moraiss** [Jp-moraiss/Soli#7]
![image](https://github.com/user-attachments/assets/03cabf8c-da49-4a78-985f-b992a609ff7f)
Falta de validação no formulário de adicionar cultura (tá podendo deixar cultura, área e linha vazio)

![image](https://github.com/user-attachments/assets/addcaa09-e616-457e-a92e-b51a979638e9)
Únicos campos obrigatórios são os das durações

**Comment by Felipemmdo** [comment]
Corrigido
