### ISSUE TITLE
Diário

### ISSUE THREAD

**Issue by Jp-moraiss** [Jp-moraiss/Soli#8]
![image](https://github.com/user-attachments/assets/4fd4d9a4-13b4-43fe-9a41-18d051e806a2)
Falta validação de formulário no diário, até agora o usuário pode salvar algo em uma data não selecionada.
![image](https://github.com/user-attachments/assets/f9d1984e-1d65-4f34-9ef3-cd344dcf193a)
e isso faz acontecer um ValidationError

**Comment by brunooassuncao** [comment]
resolvido
